using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EvilModToolkit.Services.Analysis;
using EvilModToolkit.Services.Platform;
using Microsoft.Extensions.Logging;
using NSubstitute;
using Xunit;
using Xunit.Abstractions;
using EvilModToolkit.Models;

namespace EvilModToolkit.Tests.Services.Analysis;

public class F4SePluginPerformanceTests : IDisposable
{
    private readonly ITestOutputHelper _testOutputHelper;
    private readonly string _testDataPath;
    private readonly string _tempTestPath;

    // Minimal valid .NET DLL (Base64 encoded) to simulate a plugin
    private const string MockDllBase64 = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAOJ1g/0AAAAAAAAAAOAAIiALATAAAAgAAAAGAAAAAAAAViYAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAAMmAABPAAAAAEAAAIQDAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAwJQAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAXAYAAAAgAAAACAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAIQDAAAAQAAAAAQAAAAKAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAADgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAA3JgAAAAAAAEgAAAACAAUAXCAAANQEAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICKAwAAAoAKgAAAEJTSkIBAAEAAAAAAAwAAAB2NC4wLjMwMzE5AAAAAAUAbAAAAHABAAAjfgAA3AEAAOwBAAAjU3RyaW5ncwAAAADIAwAABAAAACNVUwDMAwAAEAAAACNHVUlEAAAA3AMAAPgAAAAjQmxvYgAAAAAAAAACAAABRxQAAAkAAAAA+gEzABYAAAEAAAANAAAAAgAAAAEAAAAMAAAACwAAAAEAAAABAAAAAABoAQEAAAAAAAYA3gCqAQYAMAGqAQYAIACXAQ8AygEAAAYASwBOAQYAFwF/AQYApwB/AQYAZAB/AQYAgQB/AQYA/gB/AQYANAB/AQYAxgCqAQYA2QF4AQAAAAAIAAAAAAABAAEAAQAQAAEA4AE1AAEAAQBQIAAAAACGGJEBBgABAAkAkQEBABEAkQEGABkAkQEKACkAkQEQADEAkQEQADkAkQEQAEEAkQEQAEkAkQEQAFEAkQEQAFkAkQEQAGEAkQEBAGkAkQEGACcAWwDsAC4ACwAeAC4AEwAnAC4AGwBGAC4AIwBPAC4AKwCPAC4AMwCgAC4AOwCrAC4AQwC4AC4ASwCPAC4AUwCPAASAAAABAAAAAAAAAAAAAAAAAOABAAAKAAAAAAAAAAAAAAAVABEAAAAAAAAAAENsYXNzMQA8TW9kdWxlPgBTeXN0ZW0uUnVudGltZQBEZWJ1Z2dhYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAEFzc2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlJbmZvcm1hdGlvbmFsVmVyc2lvbkF0dHJpYnV0ZQBBc3NlbWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUAUmVmU2FmZXR5UnVsZXNBdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAFN5c3RlbS5SdW50aW1lLlZlcnNpb25pbmcAdGVtcF9pbmplY3QuZGxsAFN5c3RlbQBTeXN0ZW0uUmVmbGVjdGlvbgAuY3RvcgBTeXN0ZW0uRGlhZ25vc3RpY3MAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBEZWJ1Z2dpbmdNb2RlcwBPYmplY3QAdGVtcF9pbmplY3QAAAAAADEEe/kPrJNAlCHiK0GqXEcABCABAQgDIAABBSABARERBCABAQ4IsD9ffxHVCjoIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEABwEAAAAAPwEAGS5ORVRDb3JlQXBwLFZlcnNpb249djEwLjABAFQOFEZyYW1ld29ya0Rpc3BsYXlOYW1lCS5ORVQgMTAuMBABAAt0ZW1wX2luamVjdAAACgEABURlYnVnAAAMAQAHMS4wLjAuMAAAMwEALjEuMC4wKzcwNzFmMjkxYzUyMDkxNmRlZGRkMTMxNTZhMTZlN2UwY2IwYjFiNzYAAAgBAAsAAAAAAAAAAAAAAABllCfbAAFNUAIAAABYAAAAhCUAAIQHAAAAAAAAAAAAAAEAAAATAAAAJwAAANwlAADcBwAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAFJTRFOQJrJ+ApSORbbCrrHlaQB7AQAAAEo6XEV2aWxNb2RUb29sa2l0XHRlbXBfaW5qZWN0XG9ialxEZWJ1Z1xuZXQxMC4wXHRlbXBfaW5qZWN0LnBkYgBTSEEyNTYAkCayfgKUjkV2wq6x5WkAe2WUJ1skLTKm0GIvww2kJcsrJgAAAAAAAAAAAABFJgAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANyYAAAAAAAAAAAAAAABfQ29yRGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAAAP8lACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFhAAAAoAwAAAAAAAAAAAAAoAzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAAAQAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEiAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAZAIAAAEAMAAwADAAMAAwADQAYgAwAAAAOAAMAAEAQwBvAG0AcABhAG4AeQBOAGEAbQBlAAAAAAB0AGUAbQBwAF8AaQBuAGoAZQBjAHQAAABAAAwAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAdABlAG0AcABfAGkAbgBqAGUAYwB0AAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAxAC4AMAAuADAALgAwAAAAQAAQAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAAB0AGUAbQBwAF8AaQBuAGoAZQBjAHQALgBkAGwAbAAAACgAAgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAACAAAABIABAAAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAdABlAG0AcABfAGkAbgBqAGUAYwB0AC4AZABsAGwAAAA4AAwAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAHQAZQBtAHAAXwBpAG4AagBlAGMAdAAAAIIALwABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAArADcAMAA3ADEAZgAyADkAMQBjADUAMgAwADkAMQA2AGQAZQBkAGQAZAAxADMAMQA1ADYAYQAxADYAZQA3AGUAMABjAGIAMABiADEAYgA3ADYAAAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAADAAAAFg2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

    public F4SePluginPerformanceTests(ITestOutputHelper testOutputHelper)
    {
        _testOutputHelper = testOutputHelper;
        _testDataPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "test_data", "F4SE_Plugins");
        _tempTestPath = Path.Combine(Path.GetTempPath(), "EvilModToolkit_Tests_" + Guid.NewGuid());
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempTestPath))
        {
            try
            {
                Directory.Delete(_tempTestPath, true);
            }
            catch (Exception ex)
            {
                _testOutputHelper.WriteLine($"Failed to cleanup temp dir: {ex.Message}");
            }
        }
    }

    [Fact]
    public void ScanDirectory_PerformanceTest()
    {
        // Arrange
        var logger = Substitute.For<ILogger<F4SePluginService>>();
        var fileVersionService = Substitute.For<IFileVersionService>();
        var service = new F4SePluginService(logger, fileVersionService);

        Directory.CreateDirectory(_tempTestPath);

        // Create synthetic data to ensure the performance test is consistent and works in CI
        var dllBytes = Convert.FromBase64String(MockDllBase64);
        int pluginCount = 50; // Enough to measure basic I/O but fast enough for tests
        
        for (int i = 0; i < pluginCount; i++)
        {
            File.WriteAllBytes(Path.Combine(_tempTestPath, $"mock_plugin_{i}.dll"), dllBytes);
        }

        // Act
        var stopwatch = Stopwatch.StartNew();
        var plugins = service.ScanDirectory(_tempTestPath);
        stopwatch.Stop();

        // Assert
        _testOutputHelper.WriteLine($"ScanDirectory took {stopwatch.ElapsedMilliseconds} ms to scan {plugins.Count} plugins.");
        
        // Performance check
        Assert.True(stopwatch.ElapsedMilliseconds < 5000, "ScanDirectory performance degraded: took longer than 5 seconds.");
        
        // Functional check
        Assert.NotEmpty(plugins);
        Assert.Equal(pluginCount, plugins.Count);
    }

    [Fact]
    public async Task ModScannerService_ScanAsync_PerformanceTest()
    {
        // Arrange
        var logger = Substitute.For<ILogger<ModScannerService>>();
        var service = new ModScannerService(logger);

        var gameInfo = new GameInfo
        {
            DataPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "test_data")
        };
        var modManagerInfo = new ModManagerInfo(); // Mocked, as it's not directly used for file system interaction in this service

        // Ensure test data directory exists
        // In CI this might exist but be empty. We assert existence, but not content.
        Assert.True(Directory.Exists(gameInfo.DataPath), $"Test data directory not found: {gameInfo.DataPath}");

        var scanOptions = new ScanOptions
        {
            ScanJunkFiles = true,
            ScanWrongFormat = true,
            ScanLoosePrevis = true,
            ScanProblemOverrides = true,
            ScanErrors = true, // To enable CheckComplexSorterIni
            SkipDataScan = false
        };

        // Act
        var stopwatch = Stopwatch.StartNew();
        var results = await service.ScanAsync(gameInfo, modManagerInfo, scanOptions);
        stopwatch.Stop();

        // Assert
        _testOutputHelper.WriteLine($"ModScannerService.ScanAsync took {stopwatch.ElapsedMilliseconds} ms to find {results.Count} issues.");

        // Adjust threshold based on test data size and expected performance
        Assert.True(stopwatch.ElapsedMilliseconds < 5000, "ModScannerService.ScanAsync performance degraded: took longer than 5 seconds.");
    }
}